//Detector screen
export const GET_PROFILE = 'GET_PROFILE';
export const GET_HISTORY_DEVICE = 'GET_HISTORY_DEVICE';
export const GET_HISTORY_TIME = 'GET_HISTORY_TIME';
export const LOADING_DETECTOR = 'LOADING_DETECTOR';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const CLEAR_DETECTOR = 'CLEAN_DETECTOR';
export const DETECTORS = 'DETECTORS';
export const DEVICE_PROPERTIES = 'DEVICE_PROPERTIES';
